# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0026_auto_20180510_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='suggested_editor',
            field=models.ForeignKey(blank=True, help_text='Suggest an editorfor your article.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested_reviewers',
            field=models.TextField(blank=True, help_text='Suggest reviewers for your article,please supply name and emailaddress.', null=True),
        ),
        migrations.AddField(
            model_name='submissionconfiguration',
            name='suggest_editors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionconfiguration',
            name='suggest_reviewers',
            field=models.BooleanField(default=False),
        ),
    ]
